Lssttd 786
lsst-camera-dh/lcatr-harness pull request #3
Opened 2016-12-05 21:35 UTC by JoanneBogart

By default allows dependencies outside current run for non-production jobs.
Setting environment variable LCATR_FORCE_RUN_MATCH will force production behavior in non-productions circumstances.

2017-01-26 06:48 UTC, jchiang87 requested changes
Can you replace `Exception` in `et_wrapper.py` with something more specific so that my code doesn't have to try to catch every possible exception?  Ideally, a specialized subclass of `RuntimeError` like `EtWrapperConnectionError` would be good.  The more specific the better I think.  At a mininum, one should use `RuntimeError` if none of the other standard types apply.

2017-01-26 07:36 UTC, jchiang87 requested changes

2017-01-26 07:36 UTC, jchiang87 commented on python/lcatr/harness/job.py
> +            intRun = int(self.lims.runNumber)
This line breaks the `fake_eT.py` environment, since it never assigns `self.lims.runNumber`.

2017-01-26 07:36 UTC, jchiang87 commented on python/lcatr/harness/job.py
> +        except ValueError:
If you change this line to 
```
        except (ValueError, TypeError):
```
`fake_eT.py` will work.

2017-01-27 01:31 UTC, JoanneBogart commented
I believe the latest commit  addresses issues raised by @jchiang87

2017-01-27 03:21 UTC, jchiang87 approved these changes

2017-01-27 18:36 UTC, merged